### PR TITLE
Add FreeBSD build configuration

### PR DESCRIPTION
**Pull request by danieldk**

### CODE REVIEW

**Comment by danieldk** [comment]
Build and test without any extra features. OpenBLAS on FreeBSD is ooooold.

**Comment by danieldk** [comment]
> Build passes, tests pass, not much else to see here, right?

Nope. Boring. Just wanted to check if you are ok with adding another platform to the tests.

What about Windows?

**Comment by sebpuetz** [comment]
> What about Windows?

Travis supports rust builds for windows https://docs.travis-ci.com/user/reference/windows/#supported-languages

**Comment by danieldk** [comment]
Ah, great, so we'll just use that.

**Pull request merged**
