### PR TITLE
Fix benchmarks

### PR DESCRIPTION
**Pull request by danieldk**

### CODE REVIEW

**Comment by danieldk** [comment]
I guess we should look if we can just build them without running them.

**Comment by sebpuetz** [comment]
We don't intend to change the API anymore anyways, so I think we probably won't have to fix them again anyways

**Comment by danieldk** [comment]
Interesting, this is merged, but GitHub shows for `master` that Nicole's commit from 5 days ago is the last commit.

**Comment by sebpuetz** [comment]
My activity feed also shows that you pushed Nicole's commit 5 hours ago:
image

**Comment by danieldk** [comment]
Idd, because with branch protection we should not be able to go backwards.

**Pull request merged**
