### PR TITLE
Add benchmarks for OPQ embeddings

### PR DESCRIPTION
**Pull request by danieldk**

### CODE REVIEW

**Comment by danieldk** [comment]
Interesting lesson, now that we can measure this more exactly: there is virtually no performance difference in mmap'ed and in-memory embeddings.

I'll do a separate PR tomorrow for regular arrays. Let's see if that conclusion holds up!

**Comment by sebpuetz** [comment]
Looks like CI isn't executing all benches? https://travis-ci.org/finalfusion/finalfusion-rust/jobs/591850041#L981-L989

**Comment by danieldk** [comment]
> Looks like CI isn't executing all benches? https://travis-ci.org/finalfusion/finalfusion-rust/jobs/591850041#L981-L989

No, this is intentional, I guess we don't want CI to download all embeddings, especially once we also have the benchmarks for the non-quantized embeddings.

**Comment by sebpuetz** [comment]
> > Looks like CI isn't executing all benches? https://travis-ci.org/finalfusion/finalfusion-rust/jobs/591850041#L981-L989
> 
> No, this is intentional, I guess we don't want CI to download all embeddings, especially once we also have the benchmarks for the non-quantized embeddings.

But there are two `bench` calls in CI and only one gets executed?

**Comment by danieldk** [comment]
> But there are two `bench` calls in CI and only one gets executed?

Ah, right, the git checkout fails with:

```
fatal: reference is not a tree: 900ddcaef1c48710dc22983ba45f572ac314171c
```

**Comment by danieldk** [comment]
> > But there are two `bench` calls in CI and only one gets executed?
> 
> Ah, right, the git checkout fails with:
> 
> ```
> fatal: reference is not a tree: 900ddcaef1c48710dc22983ba45f572ac314171c
> ```

I guess that we are running into this

https://travis-ci.community/t/travis-commit-is-not-the-commit-initially-checked-out/3775

Interesting that it worked earlier.

Ps. I have also added the benchmarks for ndarray storage to this PR.

**Comment by sebpuetz** [comment]
I'm currently fetching the embeddings to also run the benches on my machine

**Comment by sebpuetz** [comment]
```
$ zsh ./benches/fetch-data.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  422M  100  422M    0     0  7123k      0  0:01:00  0:01:00 --:--:-- 7211k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3222M  100 3222M    0     0  7165k      0  0:07:40  0:07:40 --:--:-- 7198k
./benches/fetch-data.sh:14: command not found: unzstd
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 1900k    0  5271    0     0  24981      0  0:01:17 --:--:--  0:01:17 24863
curl: (23) Failed writing body (213 != 1388)
```

That failed, now trying again with `bash ./benches/fetch-data.sh`

**Comment by sebpuetz** [comment]
Nevermind, I should maybe just read the error msg and install `zstd`.

**Comment by sebpuetz** [comment]
~~~
ndarray-lookup-allround time:   [397.69 ns 401.31 ns 404.99 ns]
ndarray-mmap-lookup-allround   [716.23 ns 725.27 ns 734.36 ns]
~~~
Doesn't seem to hold for array lookups.

~~~
ndarray-lookup-known    time:   [209.85 ns 211.22 ns 212.58 ns]
ndarray-mmap-lookup-knwon   [431.25 ns 434.08 ns 436.89 ns]

ndarray-lookup-unknown  time:   [16.560 us 16.738 us 16.919 us] 
ndarray-mmap-lookup-unknown   [21.203 us 21.508 us 21.856 us]
~~~

And the difference is stable for both known and unknown.

**Comment by danieldk** [comment]
Indeed. I guess the difference may be there in quantized embeddings, but gets overwhelmed by the far more expensive operations of constructing the embedding + projection.

**Comment by sebpuetz** [comment]
> Indeed. I guess the difference may be there in quantized embeddings, but gets overwhelmed by the far more expensive operations of constructing the embedding + projection.

Weirdly enough, for me in-memory opq was slower than mmap-opq:
~~~
opq-lookup-allround     time:   [34.674 us 37.278 us 39.995 us] 
opq-mmap-lookup-allround     time:   [30.607 us 32.823 us 35.219 us]
~~~
and the margin is ~15% here. For known embeddings, there is hardly a difference:

~~~
opq-lookup-known        time:   [15.133 us 15.185 us 15.248 us] 
opq-mmap-lookup-known   time:   [15.273 us 15.332 us 15.403 us]
~~~

but for the unknowns it's quite big:

~~~
opq-lookup-unknown      time:   [841.83 us 856.30 us 870.43 us]
opq-mmap-lookup-unknown time:   [704.00 us 716.35 us 728.54 us]
~~~


Anyways, the bench is still broken, for some reason the second `cargo bench subword` tries to run the array bench which breaks because the embeddings aren't there:

https://travis-ci.org/finalfusion/finalfusion-rust/jobs/591880425#L1017-L1019

**Comment by sebpuetz** [comment]
Only when I specify the bench through `cargo bench --bench subword` is execution restricted to the subword bench:
~~~
$ cargo bench --bench subword
    Finished release [optimized] target(s) in 0.03s
     Running target/release/deps/subword-6911d74ec93bb9e8
subwords-len-10-minn-3-maxn-6                                                                             
                        time:   [770.85 ns 771.69 ns 772.56 ns]
                        change: [-0.0118% +0.2398% +0.4873%] (p = 0.07 > 0.05)
                        No change in performance detected.
Found 8 outliers among 100 measurements (8.00%)
  3 (3.00%) low mild
  4 (4.00%) high mild
  1 (1.00%) high severe
~~~
 
If I pass an argument after `cargo bench`, something still gets executed:

~~~
$ cargo bench subword 
    Finished release [optimized] target(s) in 0.03s
     Running target/release/deps/finalfusion-ebbd96b8e205053e

running 14 tests
test chunks::vocab::tests::fasttext_subword_vocab_write_read_roundtrip ... ignored
test chunks::vocab::tests::subword_vocab_correct_chunk_size ... ignored
test chunks::vocab::tests::subword_vocab_write_read_roundtrip ... ignored
test compat::fasttext::indexer::tests::subword_indices_test ... ignored
test compat::fasttext::indexer::tests::subword_indices_test_5_5 ... ignored
test subword::tests::empty_ngram_test ... ignored
test subword::tests::incorrect_max_n_test ... ignored
test subword::tests::incorrect_min_n_test ... ignored
test subword::tests::ngrams_23_test ... ignored
test subword::tests::ngrams_indices_2m_test ... ignored
test subword::tests::ngrams_test ... ignored
test subword::tests::short_ngram_test ... ignored
test subword::tests::subword_indices_2m_test ... ignored
test subword::tests::subword_indices_4_test ... ignored

test result: ok. 0 passed; 0 failed; 14 ignored; 0 measured; 41 filtered out

     Running target/release/deps/array-5d3b6b5c33ddb696
     Running target/release/deps/data-ca3b451282c08ca0

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/release/deps/quantized-5f1430c77b0fd447
     Running target/release/deps/subword-6911d74ec93bb9e8
subwords-len-10-minn-3-maxn-6                                                                             
                        time:   [773.59 ns 778.62 ns 784.26 ns]
                        change: [+0.3174% +0.8721% +1.4535%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 9 outliers among 100 measurements (9.00%)
  5 (5.00%) high mild
  4 (4.00%) high severe
~~~

Which in turn fails if an embedding file is missing:

~~~
$ cargo bench subword
[...]
     Running target/release/deps/array-5d3b6b5c33ddb696
thread 'main' panicked at 'Embedding file missing, run fetch-data.sh: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: bench failed
~~~

**Comment by danieldk** [comment]
Interesting, on my machine it reliably benches following the pattern that I give it as a normal argument. Also, according to `cargo bench --help`:

```
USAGE:
    cargo bench [OPTIONS] [BENCHNAME] [-- <args>...]
[...]
ARGS:
    <BENCHNAME>    If specified, only run benches containing this string in their names
```

What does your `cargo bench --help` say?

**Comment by sebpuetz** [comment]
My docs say the same

~~~
$ cargo bench --help
cargo-bench 
Execute all benchmarks of a local package

USAGE:
    cargo bench [OPTIONS] [BENCHNAME] [-- <args>...]
[...]
ARGS:
    <BENCHNAME>    If specified, only run benches containing this string in their names
    <args>...      Arguments for the bench binary
~~~

I can put whatever I want behind `cargo bench` without errors, although no benches are actually made. Errors happen if any of the embeddings are not there.

~~~
$ cargo bench foo                       
    Finished release [optimized] target(s) in 0.03s
     Running target/release/deps/finalfusion-ebbd96b8e205053e

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 55 filtered out

     Running target/release/deps/array-5d3b6b5c33ddb696
     Running target/release/deps/data-ca3b451282c08ca0

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/release/deps/quantized-5f1430c77b0fd447
     Running target/release/deps/subword-6911d74ec93bb9e8
~~~

What Rust version are you using?
~~~
$ cargo --version      
cargo 1.38.0 (23ef9a4ef 2019-08-20)
~~~

(In the last CI run, the git checkout failed. Maybe you can add `set -ex` to the `after-success.sh` script for a bit more verbosity?)

**Comment by danieldk** [comment]
> What Rust version are you using?
> 
> ```
> $ cargo --version      
> cargo 1.38.0 (23ef9a4ef 2019-08-20)
> ```

```
% cargo --version
cargo 1.38.0 (23ef9a4ef 2019-08-20)
```

Examples:

```
% cargo bench subword  
[...]
     Running target/release/deps/subword-6fbf9dd49ffb3402
Gnuplot not found, disabling plotting
Benchmarking subwords-len-10-minn-3-maxn-6: Collecting 100 samples in estimated                                                                                 subwords-len-10-minn-3-maxn-6                        
                        time:   [734.36 ns 737.24 ns 740.24 ns]
                        change: [+0.4798% +1.1342% +1.7865%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 5 outliers among 100 measurements (5.00%)
  5 (5.00%) high mild
```

```
% cargo bench opq-mmap
[...]
Gnuplot not found, disabling plotting
Benchmarking opq-mmap-lookup-allround: Collecting 100 samples in estimated 5.145                                                                                opq-mmap-lookup-allround                        
                        time:   [38.969 us 41.247 us 43.728 us]
                        change: [-10.054% -0.6120% +9.8273%] (p = 0.90 > 0.05)
                        No change in performance detected.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild

Benchmarking opq-mmap-lookup-known: Collecting 100 samples in estimated 5.0911 s                                                                                opq-mmap-lookup-known   time:   [21.793 us 22.629 us 23.730 us]
                        change: [+3.0562% +5.5535% +8.6740%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 7 outliers among 100 measurements (7.00%)
  5 (5.00%) high mild
  2 (2.00%) high severe

Benchmarking opq-mmap-lookup-unknown: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 5.4s or reduce sample count to 60
Benchmarking opq-mmap-lookup-unknown: Collecting 100 samples in estimated 5.3656                                                                                opq-mmap-lookup-unknown time:   [981.11 us 1.0074 ms 1.0333 ms]
                        change: [+0.3551% +4.2229% +8.2628%] (p = 0.04 < 0.05)
                        Change within noise threshold.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) low severe
  2 (2.00%) low mild
  1 (1.00%) high mild
```

**Comment by danieldk** [comment]
Oh, right, I am misreading your comments. So, `bench` works, but it still executes code of the other benchmarks. I guess it runs everything but `bench_function` becomes a noop for benchmarks that do not match.

**Comment by danieldk** [comment]
I guess we are being hit by Travis' default clone depth of 50. Latest push removes the depth, let's see what happens.

**Comment by danieldk** [comment]
> ```
> ndarray-lookup-allround time:   [397.69 ns 401.31 ns 404.99 ns]
> ndarray-mmap-lookup-allround   [716.23 ns 725.27 ns 734.36 ns]
> ```
> 
> Doesn't seem to hold for array lookups.
> 
> ```
> ndarray-lookup-known    time:   [209.85 ns 211.22 ns 212.58 ns]
> ndarray-mmap-lookup-knwon   [431.25 ns 434.08 ns 436.89 ns]
> 
> ndarray-lookup-unknown  time:   [16.560 us 16.738 us 16.919 us] 
> ndarray-mmap-lookup-unknown   [21.203 us 21.508 us 21.856 us]
> ```
> 
> And the difference is stable for both known and unknown.

BTW, what exact CPU and memory bandwidth (our numbers seem to be very similar, yours slightly better than my Core i5).

**Comment by danieldk** [comment]
Ok, CI seems to work again with the depth limit removed.

**Comment by sebpuetz** [comment]
> > ```
> > ndarray-lookup-allround time:   [397.69 ns 401.31 ns 404.99 ns]
> > ndarray-mmap-lookup-allround   [716.23 ns 725.27 ns 734.36 ns]
> > ```
> > 
> > 
> > Doesn't seem to hold for array lookups.
> > ```
> > ndarray-lookup-known    time:   [209.85 ns 211.22 ns 212.58 ns]
> > ndarray-mmap-lookup-knwon   [431.25 ns 434.08 ns 436.89 ns]
> > 
> > ndarray-lookup-unknown  time:   [16.560 us 16.738 us 16.919 us] 
> > ndarray-mmap-lookup-unknown   [21.203 us 21.508 us 21.856 us]
> > ```
> > 
> > 
> > And the difference is stable for both known and unknown.
> 
> BTW, what exact CPU and memory bandwidth (our numbers seem to be very similar, yours slightly better than my Core i5).

AMD 2700x at stock with 32gb@3200 on Ubuntu 18.04 (kernel 5.0)

**Pull request merged**
